services:
  twitch-drops-miner:
    container_name: twitch-drops-miner
    image: rangermix/twitch-drops-miner:1.3.0
    # ports:
    #   - 6080:8080
    volumes:
      - ${TDM_DATA:-./tdm}/data:/app/data
      - ${TDM_DATA:-./tdm}/logs:/app/logs
    environment:
      - TZ=${TZ:-Europe/London}

      # NOTE: this fixes the rev proxy connection issue introduced in 1.3.0
      # See https://github.com/rangermix/TwitchDropsMiner/issues/106 for details
      - FORWARDED_ALLOW_IPS=*
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
    networks:
      - rev_proxy
    labels:
      glance.name: Twitch Drop Miner
      glance.icon: di:twitch
      glance.url: https://drops.${DOMAIN:-example.com}
      glance.description: Farm Drops from Twitch
      glance.id: twitch

  terraria:
    container_name: terraria
    image: ryshe/terraria:vanilla-latest
    # ports:
    #   - 7777:7777
    volumes:
      - ${TERRARIA_DATA:-./terraria}/worlds:/root/.local/share/Terraria/Worlds
      - ${TERRARIA_DATA:-./terraria}/config.txt:/config/serverconfig.txt
      - ${TERRARIA_DATA:-./terraria}/logs:/terraria-server/logs
    environment:
      - WORLD_FILENAME=${WORLD_FILENAME}
    restart: unless-stopped
    # Attach to the container with `docker attach terraria`
    # Detach with Ctrl-p Ctrl-q
    tty: true
    stdin_open: true
    networks:
      - rev_proxy
    labels:
      glance.name: Terraria
      glance.icon: di:terraria
      glance.url: https://terraria.wiki.gg/
      glance.description: Terraria Server
      glance.id: terraria


networks:
  rev_proxy:
    external: true

